[tool.ruff]
line-length = 88
target-version = "py313"
exclude = [".venv", ".git", ".tox", "docs", "venv", "bin", "lib", "deps", "build"]

[tool.ruff.lint]
ignore = ["E501", "E203", "D202"]
select = ["E", "F", "W", "I"]

[tool.ruff.lint.isort]
known-first-party = ["homeassistant"] # Example for Home Assistant modules
known-local-folder = ["custom_components"] # Example for custom components
section-order = ["future", "standard-library", "third-party", "first-party", "local-folder"]
force-sort-within-sections = true
combine-as-imports = true
